from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, EmailStr, SecretStr
from enum import Enum


#making a user
class User(BaseModel):
    id: int
    email: EmailStr
    password_hash: SecretStr

class EventType(str, Enum):
    SCHOOL_TASK = "school_task"
    GENERAL_EVENT = "general_event"

class RegisterRequest(BaseModel):
    email: EmailStr
    password: SecretStr  # or use str if you prefer

class LoginRequest(BaseModel):
    email: EmailStr
    password: SecretStr

# Model for creating an event, owner_id will be added by the backend
class EventCreate(BaseModel):
    title: str
    start_datetime: datetime
    end_datetime: datetime
    event_type: EventType
    subject: Optional[str] = None
    priority: Optional[int] = Field(None, ge=1, le=5)
    description: Optional[str] = None
    estimated_minutes: Optional[int] = None
    status: Optional[str] = None

# Full Event Model including fields generated by the backend
class Event(EventCreate):
    id: int
    owner_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

# In-memory databases
events_db: List[Event] = []
