from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, EmailStr
from enum import Enum


class EventType(str, Enum):
    SCHOOL_TASK = "school_task"
    GENERAL_EVENT = "general_event"

# Model for creating an event, owner_id will be added by the backend
class EventBase(BaseModel):
    title: str
    start_datetime: datetime
    end_datetime: datetime
    event_type: EventType
    subject: Optional[str] = None
    priority: Optional[int] = Field(None, ge=1, le=5)
    description: Optional[str] = None
    estimated_minutes: Optional[int] = None
    status: Optional[str] = None

class EventCreate(EventBase):
    pass

# Full Event Model including fields generated by the backend
class Event(EventBase):
    id: int
    owner_id: str
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True