from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field, EmailStr
from enum import Enum

# Model for creating an event, owner_id will be added by the backend
class EventBase(BaseModel):
    title: str
    start_datetime: datetime
    end_datetime: datetime
    description: Optional[str] = None

class EventCreate(EventBase):
    pass

# Model for updating an event, all fields are optional
class EventUpdate(BaseModel):
    title: Optional[str] = None
    start_datetime: Optional[datetime] = None
    end_datetime: Optional[datetime] = None
    description: Optional[str] = None

# Full Event Model including fields generated by the backend
class Event(EventBase):
    id: int
    owner_id: str
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class AssignmentBase(BaseModel):
    title: str
    subject: str
    estimated_minutes: int
    description: Optional[str] = None

class CreateAssignment(AssignmentBase):
    pass

class UpdateAssignment(BaseModel):
    title: Optional[str] = None
    subject: Optional[str] = None
    estimated_minutes: Optional[int] = None
    description: Optional[str] = None

class Assignment(AssignmentBase):
    id: int
    owner_id: str
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True
